### ISSUE TITLE
Support for retro browsers 

### ISSUE THREAD

**Issue by ltning** [gyptazy/manpageblog#19]
Hi,

this strikes me as a perfect tool to generate html for really old browsers. Think frameless, css-less and generally wonky ones. HTML 3, at best. 

Would this be feasible?

/Eirik

**Comment by gyptazy** [comment]
Hey Eirik (@ltning),

thanks for you request and sorry for my late response!

It comes with a very small subset of CSS (see [here](https://github.com/gyptazy/manpageblog/blob/master/_assets/css/light.css)) style to avoid writing everything in a `<pre>` tag. This `manpageblog` is optimised to be very performant and minimalistic where it fills the gap of non resource hungry websites nowadays. As a result, the generated pages will be loaded very fast even in older computers but also on text only clients.

An example of `manpageblog.org` is given by the attached screenshot in the text browser `links`:
![manpageblog_in_browser_links](https://github.com/gyptazy/manpageblog/assets/4150400/5add8b75-fbb8-4f9d-8cb1-c6955dcf96aa)

You can also test and play around with it with this Container image: https://manpageblog.org/blog/manpageblock-container-image-for-docker-podman/

I hope this helps! 

Have a nice weekend!

Cheers,
gyptazy
